blog/urls.py
from django.urls import path
from .views import blogs, detail, url_in_detail_page

app_name = 'blogs'

urlpatterns = [
    path('blog-list/', blogs, name='blog-list'),
    path('url_in_detail_page/<int:day>/<int:month>/<int:year>/<slug:slug>/', url_in_detail_page,
         name='url_in_detail_page'),
    path('detail/<int:day>/<int:month>/<int:year>/<slug:slug>/', detail, name='detail'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('about/', include('about.urls', namespace='about')),
    path('blogs/', include('blog.urls', namespace='blogs')),
    path('profiles/', include('profiles.urls', namespace='profiles')),
    path('contact/', include('contact.urls', namespace='contact')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from profiles.models import Profile
from django.shortcuts import reverse
from django.db.models.signals import post_save


class Category(models.Model):
    title = models.CharField(max_length=221)

    def __str__(self):
        return self.title


class Tags(models.Model):
    title = models.CharField(max_length=221)

    def __str__(self):
        return self.title


class Travel(models.Model):
    title = models.CharField(max_length=221)

    def __str__(self):
        return self.title


class Blog(models.Model):
    author = models.ForeignKey(Profile, on_delete=models.CASCADE)
    travel = models.OneToOneField(Travel, on_delete=models.SET_NULL, null=True, blank=True)
    image = models.ImageField(upload_to='image')
    title = models.CharField(max_length=221)
    slug = models.SlugField(unique_for_date='created_date')
    text = models.TextField()
    created_date = models.TimeField(auto_now_add=True)
    modified_date = models.TimeField(auto_now=True, null=True)
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True)
    tags = models.ManyToManyField(Tags)
    # comment = models.ForeignKey(Comment, on_delete=models.CASCADE, null=True, blank=True)
    views = models.IntegerField(default=0)
    day = models.DateTimeField(auto_now=True, blank=True, null=True)

    def __str__(self):
        return f'{self.title}-->{self.id}'

    @property
    def full_url(self):
        url = reverse('blogs:url_in_detail_page', kwargs={
            'day': self.day.day,
            'month': self.day.month,
            'year': self.day.year,
            'slug': self.slug
        })
        return url


class Comment(models.Model):
    name = models.CharField(max_length=221, null=True, blank=True)
    blog = models.ForeignKey(Blog, on_delete=models.CASCADE, null=True)
    parents_comment = models.IntegerField(blank=True, null=True)
    reply_to_comment = models.ForeignKey('self', on_delete=models.SET_NULL, null=True, blank=True)
    image = models.ImageField(upload_to='comment_image', blank=True, null=True)
    email = models.EmailField(blank=True, null=True)
    number = models.IntegerField(null=True, blank=True)
    text = models.TextField()
    created_date = models.DateTimeField(auto_now_add=True, blank=True, null=True)

    def __str__(self):
        return self.name

    @property
    def get_children(self):
        children = Comment.objects.filter(parents_comment=self.id).exclude(id=self.parents_comment)
        print(type(children))
        return children


def parents_post_save(instance, sender, created, *args, **kwargs):
    if created:
        parents = instance
        while parents.reply_to_comment:
            parents = parents.reply_to_comment
        instance.parents_comment = parents.id
        instance.save()
    return instance


post_save.connect(parents_post_save, sender=Comment)


class SubBlog(models.Model):
    blog = models.ForeignKey(Blog, on_delete=models.CASCADE)
    title = models.CharField(max_length=221, blank=True, null=True)
    description = models.TextField(blank=True, null=True)

    def __str__(self):
        return self.title


class ImageSubBlog(models.Model):
    subblog = models.ForeignKey(SubBlog, on_delete=models.CASCADE)
    picture = models.ImageField(upload_to='image', )
    is_wide = models.BooleanField(default=False)

    def __str__(self):
        return str(self.id)

blog/forms.py
from django import forms
from .models import Comment


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('name', 'image', 'email', 'number', 'text')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['name'].widget.attrs.update({
            'class': 'form-control',
            'placeholder': 'name...'
        })
        self.fields['image'].widget.attrs.update({
            'class': 'form-control',
            'placeholder': 'image...'
        })
        self.fields['email'].widget.attrs.update({
            'class': 'form-control',
            'placeholder': 'email...'
        })
        self.fields['number'].widget.attrs.update({
            'class': 'form-control',
            'placeholder': 'number...'
        })
        self.fields['text'].widget.attrs.update({
            'class': 'form-control',
            'placeholder': 'message...'
        })

blog/views.py
from django.shortcuts import render, get_object_or_404, redirect, reverse
from django.core.paginator import Paginator

from profiles.models import Profile
from .forms import CommentForm
from .models import Blog, SubBlog, Category, Tags, Comment


def blogs(request):
    obj = Blog.objects.order_by('-id')
    q = request.GET.get('q')
    travel = request.GET.get('travel')
    cat = request.GET.get('cat')
    tag = request.GET.get('tag')
    if q:
        obj = obj.filter(title__icontains=q)
    if travel:
        obj = obj.filter(travel__title__exact=travel)
    if cat:
        obj = obj.filter(category__title__exact=cat)
    if tag:
        obj = obj.filter(tags__title__exact=tag)
    paginator = Paginator(obj, 1)
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)
    try:
        profile = Profile.objects.get(user_id=request.user.id)
    except:
        profile = None

    ctx = {
        'obj': page_obj,
        'profile': profile,
    }
    return render(request, 'blogs/blogs.html', ctx)


def url_in_detail_page(request, **kwargs):
    slug = kwargs.get('slug')
    day = kwargs.get('day')
    month = kwargs.get('month')
    year = kwargs.get('year')
    obj = get_object_or_404(Blog, day__day=day, day__month=month, day__year=year, slug=slug)
    obj.views += 1
    obj.save()
    url = reverse('blogs:detail', kwargs={
        'day': obj.day.day,
        'month': obj.day.month,
        'year': obj.day.year,
        'slug': obj.slug
    })
    return redirect(url)


def detail(request, **kwargs):
    slug = kwargs.get('slug')
    day = kwargs.get('day')
    month = kwargs.get('month')
    year = kwargs.get('year')
    obj = get_object_or_404(Blog, day__day=day, day__month=month, day__year=year, slug=slug)
    comments_reply = Comment.objects.filter(reply_to_comment__isnull=True, blog_id=obj.id)
    reply_to_comment_id = request.GET.get('reply_to_comment')
    try:
        profile = Profile.objects.get(user_id=request.user.id)
    except:
        profile = None
    form = CommentForm()
    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.blog = obj
            comment.reply_to_comment_id = reply_to_comment_id
            if request.user.is_authenticated:
                comment.name = str(profile.full_name)
                comment.email = profile.email
                comment.number = profile.number
                comment.image = profile.image
            comment.save()
            return redirect('.')
    obj1 = Blog.objects.order_by('-id')
    try:
        profile = Profile.objects.get(user_id=request.user.id)
    except:
        profile = None
    obj1 = obj1.filter(author=obj.author)[:3]

    ctx = {
        'obj': obj,
        'obj1': obj1,
        'profile': profile,
        'form': form,
        'comments_reply': comments_reply
    }

    return render(request, 'blogs/blog-single.html', ctx)

templates/blogs/blog-single.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

    <section class="site-section py-lg">
        <div class="container">
            <div class="row blog-entries element-animate">
                <div class="col-md-12 col-lg-8 main-content">
                    <img src="{{ obj.image.url }}" alt="Image" class="img-fluid mb-5">
                    <div class="post-meta">
                        <span class="author mr-2">
                            {% if obj.author.image %}
                                <img src="{{ obj.author.image.url }}">
                            {% else %}
                                <img src="{% static 'images/1614570234_25-p-chernaya-golova-na-belom-fone-27.png' %}"
                                     alt="">
                            {% endif %}
                            {{ obj.author.full_name }}</span>&bullet;
                        <span class="mr-2"> {{ obj.created_date }} </span> &bullet;
                        <span class="ml-2"><span class="fa fa-comments"></span> 3</span>
                    </div>
                    <h1 class="mb-4">{{ obj.title|safe }}</h1>
                    <a class="category mb-5" href="#">{{ obj.category }}</a>
                    {# <a class="category mb-5" href="#">Travel</a>#}
                    <div class="post-content-body">
                        <p>{{ obj.text|safe }}</p>


                        <div class="row mb-5">
                            {% for i in obj.subblog_set.all %}
                                {% for j in i.imagesubblog_set.all %}
                                    {% if j.is_vide %}
                                        <div class="col-md-12 mb-4">
                                            <img src="{{ j.picture.url }}" alt="Image placeholder"
                                                 class="img-fluid">
                                        </div>
                                    {% else %}
                                        <div class="col-md-6 mb-4">
                                            <img src="{{ j.picture.url }}" alt="Image placeholder"
                                                 class="img-fluid">
                                        </div>
                                    {% endif %}
                                {% endfor %}
                            {% endfor %}
                        </div>
                        <p>{{ obj.subblog_set.description|safe }}</p>
                    </div>
                    <div class="pt-5">
                        <p>Categories: <a href="#">{{ obj.category }}</a>, Tags:
                            {% for tag in obj.tags.all %}
                                <a href="#">#{{ tag }}</a>,
                            {% endfor %}


                    </div>
                    <div class="pt-5">
                        <h3 class="mb-5">{{ obj.comment_set.count }} Comments</h3>
                        <ul class="comment-list">
                            {% for i in comments_reply %}
                                <li class="comment">
                                <div class="vcard">
                                    {% if i.imege %}
                                        <img src="{{ i.image.url }}" alt="Image placeholder">
                                    {% else %}
                                        <img src="{% static 'images/1614570234_25-p-chernaya-golova-na-belom-fone-27.png' %}"
                                             alt="" style="width: 75px">
                                    {% endif %}
                                </div>
                                <div class="comment-body">
                                    <h3>{{ i.name }}</h3>
                                    <div class="meta">
                                        {{ i.created_date|date:'F d, Y H:i' }}{#January 9, 2018 at 2:21pm#}</div>
                                    <p>{{ i.text }}</p>
                                    <p><a href="?reply_to_comment={{ i.id }}#comment " class="reply rounded" >Reply</a></p>
                                </div>

                                <ul class="children">
                                    {% if i.comment_set.all %}
                                        {% for j in i.get_children %}

                                        <li class="comment">
                                            <div class="vcard">
                                                {% if j.image %}
                                                    <img src="{{ j.image.url }}" alt="Image placeholder">
                                                {% else %}
                                                    <img src="{% static 'images/1614570234_25-p-chernaya-golova-na-belom-fone-27.png' %}"
                                                         alt="">
                                                {% endif %}
                                            </div>
                                            <div class="comment-body">
                                                <h3>{{ j.name }}</h3>
                                                <h4><code>{{ j.name }}</code> to <code>{{ j.reply_to_comment }}</code></h4>
                                                <div class="meta">
                                                    {{ j.created_date|date:'F d, Y H:i' }}{#January 9, 2018 at 2:21pm#}</div>
                                                <p>{{ j.text }}</p>
                                                <p><a href="?reply_to_comment={{ j.id }} #comment" class="reply rounded">Reply</a></p>
                                            </div>
                                        </li>
                                        {% endfor %}
                                    {% endif %}
                                </ul>

                            {% endfor %}

                        </ul>

                        <div class="comment-form-wrap pt-5">
                            <h3 class="mb-5" id="comment">Leave a comment</h3>
                            <form action="#" method="post" class="p-5 bg-light">
                                {% csrf_token %}
                                {% if not request.user.is_authenticated %}
                                    <div class="form-group">
                                        <label for="name">Name *</label>
                                        {{ form.name }}
                                    </div>
                                    <div class="form-group">
                                        <label for="email">Email *</label>
                                        {{ form.email }}
                                    </div>
                                    <div class="form-group">
                                        <label for="website">Image</label>
                                        {{ form.image }}
                                    </div>
                                    <div class="form-group">
                                        <label for="website">Number</label>
                                        {{ form.number }}
                                    </div>
                                {% endif %}

                                <div class="form-group">
                                    <label for="message">Message</label>
                                    {{ form.text }}
                                </div>
                                <div class="form-group">
                                    <input type="submit" value="Post Comment" class="btn btn-primary">
                                </div>
                            </form>
                        </div>
                    </div>
                </div>

                {% include 'sidebar.html' %}

            </div>
        </div>
    </section>
    <section class="py-5">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <h2 class="mb-3 ">Related Post</h2>
                </div>
            </div>
            <div class="row">
                {% for i in obj1 %}
                    <div class="col-md-6 col-lg-4">
                        <a href="{{ i.full_url }}" class="a-block sm d-flex align-items-center height-md"
                           style="background-image: url({{ i.image.url }}); ">
                            <div class="text">
                                <div class="post-meta">
                                    <span class="category">{{ i.category }}</span>
                                    <span class="mr-2">{{ i.day|date:'F d, Y' }} </span> &bullet;
                                    <span class="ml-2"><span class="fa fa-comments"></span> 3</span>
                                </div>
                                <h3>{{ i.title|safe|slice:20 }}...</h3>
                            </div>
                        </a>
                    </div>
                {% endfor %}


            </div>
        </div>
    </section>

{% endblock %}

templates/blogs/blogs.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <link rel="stylesheet" href="{% static "css1/main.css" %}">
    <section class="site-section pt-5">
        <div class="container">
            <div class="row mb-4">
                <div class="col-md-6" id="paginator">
                    <h2 class="mb-4">All blogs</h2>
                </div>
            </div>
            <div class="row blog-entries">
                <div class="col-md-12 col-lg-8 main-content">
                    <div class="row mb-5 mt-5">
                        <div class="col-md-12">
                            {% for i in obj %}
                                <div class="post-entry-horzontal">
                                    <a href="{{ i.full_url }}">
                                        <div class="image element-animate" data-animate-effect="fadeIn"
                                             style="background-image: url({{ i.image.url }});"></div>
                                        <span class="text">
    <div class="post-meta">
    <span class="author mr-2">
         {% if i.author.image %}
             <img src="{{ i.author.image.url }}">
         {% else %}
             <img src="{% static 'images/1614570234_25-p-chernaya-golova-na-belom-fone-27.png' %}"
                  alt="">
         {% endif %}
        {{ i.author.full_name }}</span>&bullet;
    <span class="mr-2">{{ i.day|date:"F d, Y"  }} </span> &bullet;
    <span class="mr-2">{{ i.category }}</span>
    <br>
    <span class="ml-2"><span class="fa fa-comments"></span> {{ i.comment_set.count }}</span> &bullet;
    <span class="ml-2"><img src="{% static 'images/eye.png' %}" alt="" style="width: 18px" class="eye" > {{ i.views }}</span>
    </div>
    <h2>{{ i.title|slice:90 }}...</h2>
    </span>
                                    </a>
                                </div>
                            {% endfor %}
                        </div>
                    </div>
                    <div class="row mt-5">
                        {% include 'pagination.html' %}
                    </div>
                </div>

                {% include 'sidebar.html' %}

            </div>
        </div>
    </section>

{% endblock %}