blog/urls.py
from django.urls import path
from .views import blogs, detail, url_in_detail_page

app_name = 'blogs'

urlpatterns = [
    path('blog-list/', blogs, name='blog-list'),
    path('url_in_detail_page/<int:day>/<int:month>/<int:year>/<slug:slug>/', url_in_detail_page,
         name='url_in_detail_page'),
    path('detail/<int:day>/<int:month>/<int:year>/<slug:slug>/', detail, name='detail'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('about/', include('about.urls', namespace='about')),
    path('blogs/', include('blog.urls', namespace='blogs')),
    path('profiles/', include('profiles.urls', namespace='profiles')),
    path('contact/', include('contact.urls', namespace='contact')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

contact/urls.py
from django.urls import path
from .views import contact

app_name = 'contact'

urlpatterns = [
    path('contact/', contact, name='contact')
]

contact/models.py
from django.db import models


class Contact(models.Model):
    name = models.CharField(max_length=221)
    number = models.FloatField(null=True, blank=True)
    email = models.EmailField(null=True, blank=True)
    message = models.TextField()
    created_date = models.TimeField(auto_now_add=True)

    def __str__(self):
        return self.name

contact/forms.py
from django import forms
from .models import Contact


class ContactForm(forms.ModelForm):
    class Meta:
        model = Contact
        fields = ('name', 'number', 'email', 'message')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['name'].widget.attrs.update({
            'class': 'form-control',
            'placeholder': 'name..',
        })
        self.fields['number'].widget.attrs.update({
            'class': 'form-control',
            'placeholder': 'Your number..',
        })
        self.fields['email'].widget.attrs.update({
            'class': 'form-control',
            'placeholder': 'Your email..',
        })
        self.fields['message'].widget.attrs.update({
            'class': 'form-control',
            'placeholder': 'Your message..',
        })

contact/views.py
from django.shortcuts import render, redirect
from profiles.models import Profile
from .forms import ContactForm


def contact(request):
    try:
        profile = Profile.objects.get(user_id=request.user.id)
    except:
        profile = None
    form = ContactForm()
    if request.method == "POST":
        form = ContactForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('blogs:blog-list')
    ctx = {
        'profile': profile,
        'form': form
    }
    return render(request, 'contact/contact.html', ctx)

templates/contact/contact.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

    <section class="site-section">
        <div class="container">
            <div class="row mb-4">
                <div class="col-md-6">
                    <h1>Contact Me</h1>
                </div>
            </div>
            <div class="row blog-entries">
                <div class="col-md-12 col-lg-8 main-content">
                    <form action="#" method="post">
                        {% csrf_token %}
                        <div class="row">
                            <div class="col-md-12 form-group">
                                <label for="id_name">Name</label>
                                {{ form.name }}
                            </div>
                            <div class="col-md-12 form-group">
                                <label for="id_number">Phone</label>
                                {{ form.number }}
                            </div>
                            <div class="col-md-12 form-group">
                                <label for="id_email">Email</label>
                                {{ form.email }}
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-12 form-group">
                                <label for="id_message">Write Message</label>
                                {{ form.message }}
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-6 form-group">
                                <input type="submit" value="Send Message" class="btn btn-primary">
                            </div>
                        </div>
                    </form>
                </div>

                {% include 'sidebar.html' %}

            </div>
        </div>
    </section>

{% endblock %}