about/urls.py
from django.urls import path
from .views import about
app_name = 'about'


urlpatterns = [
    path('about/', about, name='about')
]

blog/urls.py
from django.urls import path
from .views import blogs, detail, url_in_detail_page

app_name = 'blogs'

urlpatterns = [
    path('blog-list/', blogs, name='blog-list'),
    path('url_in_detail_page/<int:day>/<int:month>/<int:year>/<slug:slug>/', url_in_detail_page,
         name='url_in_detail_page'),
    path('detail/<int:day>/<int:month>/<int:year>/<slug:slug>/', detail, name='detail'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('about/', include('about.urls', namespace='about')),
    path('blogs/', include('blog.urls', namespace='blogs')),
    path('profiles/', include('profiles.urls', namespace='profiles')),
    path('contact/', include('contact.urls', namespace='contact')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

contact/urls.py
from django.urls import path
from .views import contact

app_name = 'contact'

urlpatterns = [
    path('contact/', contact, name='contact')
]

main/urls.py
from django.urls import path
from .views import home

app_name = 'main'

urlpatterns = [
    path('', home, name='home')
]

profiles/urls.py
from django.urls import path
from .views import mylogin, mylogaut, myregistration

app_name = 'profiles'

urlpatterns = [
    path('login/', mylogin, name='login'),
    path('logaut/', mylogaut, name='logaut'),
    path('registration/', myregistration, name='registration'),
]

templates/base.html
<!doctype html>
<html lang="en">
{% load static %}
<!-- Mirrored from preview.colorlib.com/theme/wordify/index.html by HTTrack Website Copier/3.x [XR&CO'2014], Fri, 09 Jun 2023 15:54:39 GMT -->
<head>
    <title>Colorlib Wordify &mdash; Minimal Blog Template</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link href="https://fonts.googleapis.com/css?family=Josefin+Sans:300,%20400,700|Inconsolata:400,700"
          rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'css/animate.css' %}">
    <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'fonts/ionicons/css/ionicons.min.css' %}">
    <link rel="stylesheet" href="{% static 'fonts/fontawesome/css/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'fonts/flaticon/font/flaticon.css' %}">

    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css1/main.css' %}">
    <script nonce="a84429d3-4494-40ba-a6d1-97d62eee2b7d">(function (w, d) {
        !function (dK, dL, dM, dN) {
            dK[dM] = dK[dM] || {};
            dK[dM].executed = [];
            dK.zaraz = {deferred: [], listeners: []};
            dK.zaraz.q = [];
            dK.zaraz._f = function (dO) {
                return function () {
                    var dP = Array.prototype.slice.call(arguments);
                    dK.zaraz.q.push({m: dO, a: dP})
                }
            };
            for (const dQ of ["track", "set", "debug"]) dK.zaraz[dQ] = dK.zaraz._f(dQ);
            dK.zaraz.init = () => {
                var dR = dL.getElementsByTagName(dN)[0], dS = dL.createElement(dN),
                    dT = dL.getElementsByTagName("title")[0];
                dT && (dK[dM].t = dL.getElementsByTagName("title")[0].text);
                dK[dM].x = Math.random();
                dK[dM].w = dK.screen.width;
                dK[dM].h = dK.screen.height;
                dK[dM].j = dK.innerHeight;
                dK[dM].e = dK.innerWidth;
                dK[dM].l = dK.location.href;
                dK[dM].r = dL.referrer;
                dK[dM].k = dK.screen.colorDepth;
                dK[dM].n = dL.characterSet;
                dK[dM].o = (new Date).getTimezoneOffset();
                if (dK.dataLayer) for (const dX of Object.entries(Object.entries(dataLayer).reduce(((dY, dZ) => ({...dY[1], ...dZ[1]})), {}))) zaraz.set(dX[0], dX[1], {scope: "page"});
                dK[dM].q = [];
                for (; dK.zaraz.q.length;) {
                    const d_ = dK.zaraz.q.shift();
                    dK[dM].q.push(d_)
                }
                dS.defer = !0;
                for (const ea of [localStorage, sessionStorage]) Object.keys(ea || {}).filter((ec => ec.startsWith("_zaraz_"))).forEach((eb => {
                    try {
                        dK[dM]["z_" + eb.slice(7)] = JSON.parse(ea.getItem(eb))
                    } catch {
                        dK[dM]["z_" + eb.slice(7)] = ea.getItem(eb)
                    }
                }));
                dS.referrerPolicy = "origin";
                dS.src = "../../cdn-cgi/zaraz/sd0d9.js?z=" + btoa(encodeURIComponent(JSON.stringify(dK[dM])));
                dR.parentNode.insertBefore(dS, dR)
            };
            ["complete", "interactive"].includes(dL.readyState) ? zaraz.init() : dK.addEventListener("DOMContentLoaded", zaraz.init)
        }(w, d, "zarazData", "script");
    })(window, document);</script>
</head>
<body>
<div class="wrap">
    <header role="banner">
        <div class="top-bar">
            <div class="container">
                <div class="row">
                    <div class="col-9 social">
                        <a href="#"><span class="fa fa-twitter"></span></a>
                        <a href="#"><span class="fa fa-facebook"></span></a>
                        <a href="#"><span class="fa fa-instagram"></span></a>
                        <a href="#"><span class="fa fa-youtube-play"></span></a>
                    </div>
                    <div class="col-1 ">
                        {% if request.user.is_authenticated %}
                            <h5 class="mybutton">
                                <a class="nav-link" href="{% url 'profiles:logaut' %}">Logaut</a>
                            </h5>
                        {% else %}
                            <h5 class="mybutton">
                                <a class="nav-link" href="{% url 'profiles:login' %}">Login</a>
                                <a class="nav-link" href="{% url 'profiles:registration' %}">Registration</a>
                            </h5>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
        <div class="container logo-wrap">
            <div class="row pt-5">
                <div class="col-12 text-center">
                    <a class="absolute-toggle d-block d-md-none" data-toggle="collapse" href="#navbarMenu" role="button"
                       aria-expanded="false" aria-controls="navbarMenu"><span class="burger-lines"></span></a>
                    <h1 class="site-logo"><a href="{% url 'main:home' %}">Wordify</a></h1>
                </div>
            </div>
        </div>

        {% include 'navbar.html' %}

    </header>

    <div class="messages">
        {% for i in messages %}
            {% if 'success' in i.tags %}
                <div class="alert alert-primary " role="alert">{{ i }}</div>
            {% elif 'info' in i.tags %}
                <div class="alert alert-info" role="alert">{{ i }}</div>
            {% elif 'error' in i.tags %}
                <div class="alert alert-danger" role="alert">{{ i }}</div>
            {% endif %}
        {% endfor %}
    </div>


    {% block content %}

    {% endblock %}

    {% include 'footer.html' %}

</div>

<div id="loader" class="show fullscreen">
    <svg class="circular" width="48px" height="48px">
        <circle class="path-bg" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke="#eeeeee"/>
        <circle class="path" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke-miterlimit="10"
                stroke="#f4b214"/>
    </svg>
</div>
<script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
<script src="{% static 'js/jquery-migrate-3.0.0.js' %}"></script>
<script src="{% static 'js/popper.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/owl.carousel.min.js' %}"></script>
<script src="{% static 'js/jquery.waypoints.min.js' %}"></script>
<script src="{% static 'js/jquery.stellar.min.js' %}"></script>
<script src="{% static 'js/main.js' %}"></script>

<script async src="https://www.googletagmanager.com/gtag/js?id=UA-23581568-13"></script>
<script>
    window.dataLayer = window.dataLayer || [];

    function gtag() {
        dataLayer.push(arguments);
    }

    gtag('js', new Date());

    gtag('config', 'UA-23581568-13');
</script>
<script defer src="https://static.cloudflareinsights.com/beacon.min.js/v52afc6f149f6479b8c77fa569edb01181681764108816"
        integrity="sha512-jGCTpDpBAYDGNYR5ztKt4BQPGef1P0giN6ZGVUi835kFF88FOmmn8jBQWNgrNd8g/Yu421NdgWhwQoaOPFflDw=="
        data-cf-beacon='{"rayId":"7d4a87f2cc1210a6","version":"2023.4.0","b":1,"token":"cd0b4b3a733644fc843ef0b185f98241","si":100}'
        crossorigin="anonymous"></script>
</body>

<!-- Mirrored from preview.colorlib.com/theme/wordify/index.html by HTTrack Website Copier/3.x [XR&CO'2014], Fri, 09 Jun 2023 15:54:39 GMT -->
</html>

templates/footer.html
{% load static %}
{% load simple_tags %}
{% latest_blogs as lates %}

<footer class="site-footer">
<div class="container">
<div class="row mb-5">
<div class="col-md-4">
<h3>About Us</h3>
<p class="mb-4">
<img src="{% static 'images/img_1.jpg' %}" alt="Image placeholder" class="img-fluid">
</p>
<p>Lorem ipsum dolor sit amet sa ksal sk sa, consectetur adipisicing elit. Ipsa harum inventore reiciendis. <a href="#">Read More</a></p>
</div>
<div class="col-md-6 ml-auto">
<div class="row">
<div class="col-md-7">
<h3>Latest Post</h3>
<div class="post-entry-sidebar">
<ul>

    {% for i in lates %}
        <li>
            <a href="{{ i.full_url }}">
                <img src="{{ i.image.url }}" alt="Image placeholder" class="mr-4">
                <div class="text">
                    <h4>{{ i.title|slice:50 }}..</h4>
                    <div class="post-meta">
                        <span class="mr-2">{{ i.day|date:'F d, Y' }}</span>
                        <span class="ml-2"><span class="fa fa-comments"></span> {{ i.comment_set.count }}</span>
                    </div>
                </div>
            </a>
        </li>
    {% endfor %}

</ul>
</div>
</div>
<div class="col-md-1"></div>
<div class="col-md-4">
<div class="mb-5">
<h3>Quick Links</h3>
<ul class="list-unstyled">
<li><a href="#">About Us</a></li>
<li><a href="#">Travel</a></li>
<li><a href="#">Adventure</a></li>
<li><a href="#">Courses</a></li>
<li><a href="#">Categories</a></li>
</ul>
</div>
<div class="mb-5">
<h3>Social</h3>
<ul class="list-unstyled footer-social">
<li><a href="#"><span class="fa fa-twitter"></span> Twitter</a></li>
<li><a href="#"><span class="fa fa-facebook"></span> Facebook</a></li>
<li><a href="#"><span class="fa fa-instagram"></span> Instagram</a></li>
<li><a href="#"><span class="fa fa-vimeo"></span> Vimeo</a></li>
<li><a href="#"><span class="fa fa-youtube-play"></span> Youtube</a></li>
<li><a href="#"><span class="fa fa-snapchat"></span> Snapshot</a></li>
</ul>
</div>
</div>
</div>
</div>
</div>
<div class="row">
<div class="col-md-12 text-center">
<p class="small">

Copyright &copy; <script data-cfasync="false" src="../../cdn-cgi/scripts/5c5dd728/cloudflare-static/email-decode.min.js"></script><script>document.write(new Date().getFullYear());</script> All Rights Reserved | This template is made with <i class="fa fa-heart text-danger" aria-hidden="true"></i> by <a href="https://colorlib.com/" target="_blank">Colorlib</a>

</p>
</div>
</div>
</div>
</footer>

templates/navbar.html
{% load static %}
{% load simple_tags %}
{% category_my as category %}
{% tags_my as tag %}
{% travel_my as travel %}
<nav class="navbar navbar-expand-md  navbar-light bg-light">
    <div class="container">
        <div class="collapse navbar-collapse" id="navbarMenu">
            <ul class="navbar-nav mx-auto">
                <li class="nav-item">
                    <a class="nav-link active" href="{% url 'main:home' %}">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'blogs:blog-list' %}">Blogs</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="dropdown04"
                       data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Travel</a>
                    <div class="dropdown-menu" aria-labelledby="dropdown04">
                        {% for i in travel %}
                            <a class="dropdown-item"
                               href="{% url 'blogs:blog-list' %}?travel={{ i.title }}">{{ i.title }}</a>
                        {% endfor %}
                    </div>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="../about/category.html" id="dropdown05"
                       data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Categories</a>
                    <div class="dropdown-menu" aria-labelledby="dropdown05">
                        {% for i in category %}
                            <a class="dropdown-item"
                               href="{% url 'blogs:blog-list' %}?cat={{ i.title }}">{{ i.title }}</a>
                        {% endfor %}
                    </div>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'about:about' %}">About</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'contact:contact' %}">Contact</a>
                </li>


            </ul>
        </div>
    </div>
</nav>

templates/pagination.html
<div class="col-md-12 text-center">
    <nav aria-label="Page navigation" class="text-center">
        <ul class="pagination">
            {% if obj.has_previous %}
                <li class="page-item "><a class="page-link"
                                          href="?page={{ obj.previous_page_number }} #paginator">&lt;</a></li>
            {% endif %}

            {% for i in obj.paginator.page_range %}
                {% if i == obj.number %}
                    <li class="page-item active"><a class="page-link">{{ i }}</a></li>
                {% else %}
                    <li class="page-item"><a class="page-link" href="?page={{ i }} #paginator">{{ i }}</a></li>
                {% endif %}
            {% endfor %}

            {% if obj.has_next %}
                <li class="page-item"><a class="page-link" href="?page={{ obj.next_page_number }} #paginator">&gt;</a>
                </li>
            {% endif %}

        </ul>
    </nav>
</div>

templates/sidebar.html
{% load static %}
{% load simple_tags %}
{% category_my as category %}
{% tags_my as tag %}
{% popular_blogs as popular %}

<div class="col-md-12 col-lg-4 sidebar">
    <div class="sidebar-box search-form-wrap">
        <form action="{% url 'blogs:blog-list' %}" class="search-form">
            {% csrf_token %}
            <div class="form-group">
                <span class="icon fa fa-search"></span>
                <input type="text" name="q" class="form-control" id="s"
                       placeholder="Type a keyword and hit enter">
            </div>
        </form>
    </div>
    {% if profile %}
        <div class="sidebar-box">
            <div class="bio text-center">
                {% if profile.image %}
                    <img src="{{ profile.image.url }}" alt="Image Placeholder" class="img-fluid">
                {% else %}
                    <img src="{% static 'images/1614570234_25-p-chernaya-golova-na-belom-fone-27.png' %}"
                         alt="Image Placeholder" class="img-fluid">
                {% endif %}

                <div class="bio-body">
                    <h2>{{ profile.full_name }}</h2>
                    <p>{{ profile.bio|safe|slice:150 }}...</p>
                    <p><a href="{% url 'about:about' %}" class="btn btn-primary btn-sm rounded">Read my bio</a></p>
                    <p class="social">
                        <a href="#" class="p-2"><span class="fa fa-facebook"></span></a>
                        <a href="#" class="p-2"><span class="fa fa-twitter"></span></a>
                        <a href="#" class="p-2"><span class="fa fa-instagram"></span></a>
                        <a href="#" class="p-2"><span class="fa fa-youtube-play"></span></a>
                    </p>
                </div>
            </div>
        </div>
    {% endif %}


    <div class="sidebar-box">
        <h3 class="heading">Popular Posts</h3>
        <div class="post-entry-sidebar">
            <ul>
                {% for i in popular %}
                    <li>
                        <a href="{{ i.full_url }}">
                            <img src="{{ i.image.url }}" alt="Image placeholder" class="mr-4">
                            <div class="text">
                                <h4>{{ i.title|safe|slice:25 }}..</h4>
                                <div class="post-meta">
                                    <span class="mr-2"> {{ i.day|date:"F d, Y"  }}</span>
                                </div>
                            </div>
                        </a>
                    </li>
                {% endfor %}
            </ul>
        </div>
    </div>

    <div class="sidebar-box">
        <h3 class="heading">Categories</h3>
        <ul class="categories">

            {% for i in category %}
                <li><a href="{% url 'blogs:blog-list' %}?cat={{ i.title }}">{{ i }} <span>{{ i.blog_set.count }}</span></a>
                </li>
            {% endfor %}

        </ul>
    </div>

    <div class="sidebar-box">
        <h3 class="heading">Tags</h3>
        <ul class="tags">

            {% for i in tag %}
                <li><a href="{% url 'blogs:blog-list' %}?tag={{ i.title }}">{{ i }}</a></li>
            {% endfor %}

        </ul>
    </div>
</div>